image: node:latest

before_script:
- npm install

cache:
    paths:
    - node_modules/

build:
    stage: build
    script:
    - npm run build
    artifacts:
      paths:
      - dist/mdn-search.zip